mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tpadsz.entity
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/views/
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.51.75:3306/test?useUnicode=true&characterEncoding=utf8
      password: root
      username: root
      type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 192.168.51.75
    port: 6379
    database: 1
  http:
    encoding:
      charset: utf-8
      force: true
  profiles:
    active: dev
logging:
  file: /mnt/shared/odelic/log/log.log
#server:
#  servlet:
#    context-path: /helloboot
#debug: true
